blueprint:
  name: FINK - Ikea Remote Z2M 4 Button 1 Light
  description: "Controls a light with a switch given by device. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work.\n\nAlso 4 custom actions for the arrow keys"
  domain: automation
  input:
    source_switch:
      name: Ikea Remote Z2M Switch
      description: The switch-action which triggers this automation.
      selector:
        device:
          filter:
            - integration: mqtt
    target_light:
      name: Target Light
      description: the light you want to control.
      selector:
        target:
    button_left_click:
      name: Left button - short press
      description: Action to run when SHORT press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      description: Action to run when HOLD press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      description: Action to run when SHORT press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      description: Action to run when HOLD press on RIGHT arrow button
      default: []
      selector:
        action: {}
alias: Ikea Remote Z2M 4 Button 1 Light
description: ""
trigger:
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "on"
    id: "on"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "off"
    id: "off"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_up
    id: long_press_up
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_down
    id: long_press_down
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_left_click
    id: arrow_left_click
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_right_click
    id: arrow_right_click
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_left_hold
    id: arrow_left_hold
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_right_hold
    id: arrow_right_hold

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - long_press_up
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - long_press_down
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -5
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - arrow_right_click
        sequence: !input "button_right_click"
      - conditions:
          - condition: trigger
            id:
              - arrow_left_click
        sequence: !input "button_left_click"
      - conditions:
          - condition: trigger
            id:
              - arrow_right_hold
        sequence: !input "button_right_hold"
      - conditions:
          - condition: trigger
            id:
              - arrow_left_hold
        sequence: !input "button_left_hold"
mode: restart
max_exceeded: silent
