blueprint:
  name: FINK - Ikea Remote Z2M 4 Button 2 lights
  description: "Controls a light with a switch given by device. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work."
  domain: automation
  input:
    source_switch:
      name: Ikea Remote Z2M Switch
      description: The switch to trigger this automation.
      selector:
        device:
          filter:
            - integration: mqtt
    target_light:
      name: Target Light
      description: The light you want to control.
      selector:
        target:
    target_light_2:
      name: Target Light 2
      description: The light you want to control with the left and right button.
      selector:
        target:
alias: Ikea Remote Z2M 4 Button
description: ""
trigger:
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "on"
    id: "on"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "off"
    id: "off"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_up
    id: long_press_up
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_down
    id: long_press_down
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_left_click
    id: arrow_left_click
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_right_click
    id: arrow_right_click
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_left_hold
    id: arrow_left_hold
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_right_hold
    id: arrow_right_hold
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_stop
    id: brightness_stop
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_right_release
    id: arrow_right_release
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: arrow_left_release
    id: arrow_left_release

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - long_press_up
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - long_press_down
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -5
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - arrow_right_click
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light_2
      - conditions:
          - condition: trigger
            id:
              - arrow_left_click
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light_2
      - conditions:
          - condition: trigger
            id:
              - arrow_right_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input target_light_2
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - arrow_left_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -5
                  target: !input target_light_2
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
mode: restart
