blueprint:
  name: FINK - Motion activated light with lux.
  description: Turns on a light when motion is detected and luminance is below a specified threshold, turns off after no motion for a set time.
  domain: automation
  input:
    motion_sensor_entity:
      name: Motion Sensor Entity
      description: The entity that triggers motion.
      selector:
        entity:
          domain: binary_sensor

    light_entity:
      name: Light Entity
      description: The light to be controlled.
      selector:
        entity:
          domain: light

    luminance_entity:
      name: Luminance Sensor
      description: The sensor entity that measures luminance.
      selector:
        entity:
          domain: sensor

    luminance_threshold:
      name: Luminance Threshold
      description: The luminance level below which the light will turn on.
      default: 100
      selector:
        number:
          min: 0
          max: 2000
          unit_of_measurement: lux

    no_motion_wait_time:
      name: No Motion Wait Time
      description: Time to wait with no motion before turning off the light.
      default: 30
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

alias: Bewegunsmelder
description: ""
trigger:
  - platform: state
    entity_id: !input "motion_sensor_entity"
    from: "off"
    to: "on"
    id: "on"
  - platform: state
    entity_id: !input "motion_sensor_entity"
    from: "on"
    to: "off"
    for:
      seconds: !input "no_motion_wait_time"
    id: "off"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
          - condition: numeric_state
            entity_id: !input "luminance_entity"
            below: !input "luminance_threshold"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light_entity"
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input "light_entity"
mode: restart
