blueprint:
  name: FINK - Motion-Activated Light with Conditional Lux
  description: Turns on a light when motion is detected, but only if the luminance is below a specified threshold. If luminance is above the threshold, the automation does nothing.
  domain: automation
  input:
    motion_sensor_entity:
      name: Motion Sensor Entity
      description: "Entity that triggers motion, e.g., binary_sensor.motion_sensor."
      selector:
        entity:
          domain: binary_sensor

    light_entity:
      name: Light Entity
      description: "Light to be controlled, e.g., light.living_room."
      selector:
        entity:
          domain: light

    luminance_entity:
      name: Luminance Sensor
      description: "Sensor entity measuring luminance, e.g., sensor.luminance_sensor."
      selector:
        entity:
          domain: sensor

    luminance_threshold:
      name: Luminance Threshold
      description: "Luminance level (in lux) below which the light turns on."
      default: 50
      selector:
        number:
          min: 0
          max: 2000
          unit_of_measurement: lux

    no_motion_wait_time:
      name: No Motion Wait Time
      description: "Time (in seconds) to wait with no motion before turning off the light."
      default: 30
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input "motion_sensor_entity"
    from: "off"
    to: "on"
    id: "motion_detected"
  - platform: state
    entity_id: !input "motion_sensor_entity"
    from: "on"
    to: "off"
    for:
      seconds: !input "no_motion_wait_time"
    id: "no_motion"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "motion_detected"
          - condition: numeric_state
            entity_id: !input "luminance_entity"
            below: !input "luminance_threshold"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input "light_entity"
      - conditions:
          - condition: trigger
            id: "no_motion"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input "light_entity"

mode: restart
