blueprint:
  name: FINK - Tradfri 2 Button
  description: "Controls a light with a switch given by ENTITY. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work."
  domain: automation
  input:
    source_switch:
      name: Tradfri Switch
      description: The switch to trigger this automation.
      selector:
        device:
          filter:
            - integration: mqtt
    target_light:
      name: Target Light
      description: The light you want to control.
      selector:
        target:

alias: Tradfri 2 Button
description: ""
trigger:
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "on"
    id: "on"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: "off"
    id: "off"
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_up
    id: long_press_up
  - trigger: device
    domain: mqtt
    device_id: !input source_switch
    type: action
    subtype: brightness_move_down
    id: long_press_down

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - action: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - brightness_move_up
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - brightness_move_down
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -5
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50

mode: restart
